# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160224_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to='/home/user/mydevelop/python_learn/python_way/mysite/tmp'),
        ),
    ]
