# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160225_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to='tmp'),
        ),
    ]
